#pragma once

#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define MEM_ALIGNMENT 4
#define MEM_SIZE (64 * 1024)
#define MEMP_NUM_PBUF 32
#define MEMP_NUM_TCP_PCB 12
#define MEMP_NUM_TCP_PCB_LISTEN 4
#define MEMP_NUM_TCP_SEG 64
#define PBUF_POOL_SIZE 32
#define TCP_MSS 1460
#define TCP_WND (8 * TCP_MSS)
#define TCP_SND_BUF (8 * TCP_MSS)
#define TCP_SND_QUEUELEN ((4 * TCP_SND_BUF + TCP_MSS - 1) / TCP_MSS)
#define LWIP_NETIF_HOSTNAME 1

#define LWIP_MDNS_RESPONDER 1
#define LWIP_IGMP 1
#define LWIP_NUM_NETIF_CLIENT_DATA 1
#define MDNS_RESP_USENETIF_EXTCALLBACK 1
#define MEMP_NUM_SYS_TIMEOUT (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 3)

#define LWIP_HTTPD_CGI 1
#define LWIP_HTTPD_SUPPORT_POST 1
#define LWIP_HTTPD_CUSTOM_FILES 1
#define LWIP_HTTPD_FILE_EXTENSION 1
#define LWIP_HTTPD_DYNAMIC_HEADERS 1
#define LWIP_HTTPD_MAX_REQ_LENGTH 1024
#define LWIP_HTTPD_MAX_REQUEST_URI_LEN 128
#define LWIP_HTTPD_POST_MANUAL_WND 0
#define HTTPD_FSDATA_FILE "pico_fsdata.inc"

